version: 2
workflows:
  version: 2
  main:
    jobs:
      - php56-build
      - php70-build
      - php71-build
      - php72-build
      - php73-build
      - lint:
          requires:
            - php56-build
            - php70-build
            - php71-build
            - php72-build
            - php73-build

job-references:
  mysql_image: &mysql_image
    circleci/mysql:5.6

  restore_composer: &restore_composer
    keys:
      - v1-dependencies-{{ checksum "composer.json" }}
      - v1-dependencies-

  install_composer: &install_composer
    name: "Install Composer dependencies"
    command: composer install -n --prefer-dist

  save_composer: &save_composer
    key: v1-dependencies-{{ checksum "composer.json" }}
    paths:
      - vendor

  restore_npm: &restore_npm
    keys:
      - node-v1-{{ checksum "package.json" }}
      - node-v1-

  install_npm: &install_npm
    name: "Install NPM dependencies"
    command: |
      sudo npm install --global gulp-cli
      npm install

  save_npm: &save_npm
    key: node-v1-{{ checksum "package.json" }}
    paths:
      - node_modules

  install_dependencies: &install_dependencies
    name: "Install Dependencies"
    command: |
      sudo apt-get update && sudo apt-get install subversion
      sudo -E docker-php-ext-install mysqli
      sudo sh -c "printf '\ndeb http://ftp.us.debian.org/debian sid main\n' >> /etc/apt/sources.list"
      sudo apt-get update && sudo apt-get install mysql-client-5.7

  php_job: &php_job
    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
    steps:
      - checkout

      - run: *install_dependencies

      - restore_cache: *restore_composer
      - run: *install_composer
      - save_cache: *save_composer

      - restore_cache: *restore_npm
      - run: *install_npm
      - save_cache: *save_npm

      - run:
          name: "Run Tests"
          command: |
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
            gulp unit

jobs:
  php56-build:
    <<: *php_job
    docker:
      - image: circleci/php:5.6-node
      - image: *mysql_image

  php70-build:
    <<: *php_job
    docker:
      - image: circleci/php:7.0-node
      - image: *mysql_image

  php71-build:
    <<: *php_job
    docker:
      - image: circleci/php:7.1-node
      - image: *mysql_image

  php72-build:
    <<: *php_job
    docker:
      - image: circleci/php:7.2-node
      - image: *mysql_image

  php73-build:
    <<: *php_job
    docker:
      - image: circleci/php:7.3-node
      - image: *mysql_image

  lint:
    docker:
      - image: circleci/php:7.3-node
    steps:
      - checkout

      - restore_cache: *restore_composer
      - run: *install_composer
      - save_cache: *save_composer

      - restore_cache: *restore_npm
      - run: *install_npm
      - save_cache: *save_npm

      - run: gulp lint
